//HintName: TestClassId.g.cs
// <auto-generated>
// This code was generated by a tool.
// Name: Minerals.AutoDomain.Generators
// Version: {Removed}
// </auto-generated>
[global::System.Diagnostics.DebuggerNonUserCode]
[global::System.Runtime.CompilerServices.CompilerGenerated]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public readonly struct TestClassId : global::System.IEquatable<TestClassId>
{
    public int Value => _value;

    private readonly int _value;

    public TestClassId(int value)
    {
        _value = value;
    }

    public bool Equals(TestClassId other)
    {
        return other.Value.Equals(Value);
    }

    public override bool Equals(object obj)
    {
        return obj is TestClassId other && other.Value.Equals(Value);
    }

    public override int GetHashCode()
    {
        return Value.GetHashCode();
    }

    public static bool operator ==(TestClassId left, TestClassId right)
    {
        return left.Value.Equals(right.Value);
    }

    public static bool operator !=(TestClassId left, TestClassId right)
    {
        return !left.Value.Equals(right.Value);
    }
}