//HintName: ExampleDomainEvent.g.cs
// <auto-generated>
// This code was generated by a tool.
// Name: Minerals.AutoDomain.Generators
// Version: {Removed}
// </auto-generated>
[global::System.Diagnostics.DebuggerNonUserCode]
[global::System.Runtime.CompilerServices.CompilerGenerated]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public readonly partial struct ExampleDomainEvent : global::Minerals.AutoDomain.IDomainEvent
{
    public int ExampleNumber { get; }
    public string ExampleText { get; }

    public ExampleDomainEvent(int exampleNumber, string exampleText)
    {
        ExampleNumber = exampleNumber;
        ExampleText = exampleText;
    }
}