//HintName: ExampleDomainEvent.g.cs
// <auto-generated>
// This code was generated by a tool.
// Name: Minerals.AutoDomain
// Version: {Removed}
// </auto-generated>
[global::System.Diagnostics.DebuggerNonUserCode]
[global::System.Runtime.CompilerServices.CompilerGenerated]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public sealed record ExampleDomainEvent : global::Minerals.AutoDomain.IDomainEvent
{
    public TestClassId TestClassId { get; private set; }
    public int Property1 { get; private set; }

    public ExampleDomainEvent(TestClassId testClassId, int property1)
    {
        TestClassId = testClassId;
        Property1 = property1;
    }
}