//HintName: TestEvent.g.cs
// <auto-generated>
// This code was generated by a tool.
// Name: Minerals.AutoDomain.Generators
// Version: {Removed}
// </auto-generated>
[global::System.Diagnostics.DebuggerNonUserCode]
[global::System.Runtime.CompilerServices.CompilerGenerated]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public readonly partial struct TestEvent : global::Minerals.AutoDomain.IDomainEvent, global::System.IEquatable<TestEvent>
{
    public bool Equals(TestEvent other)
    {
        return other.Property1.Equals(Property1);
    }

    public override bool Equals(object obj)
    {
        return obj is TestEvent other && other.Property1.Equals(Property1);
    }

    public override int GetHashCode()
    {
        return global::System.HashCode.Combine(Property1);
    }

    public static bool operator ==(TestEvent left, TestEvent right)
    {
        return left.Property1.Equals(right.Property1);
    }

    public static bool operator !=(TestEvent left, TestEvent right)
    {
        return !left.Property1.Equals(right.Property1);
    }
}