//HintName: TestClass.g.cs
// <auto-generated>
// This code was generated by a tool.
// Name: Minerals.AutoDomain.Generators
// Version: {Removed}
// </auto-generated>
[global::System.Diagnostics.DebuggerNonUserCode]
[global::System.Runtime.CompilerServices.CompilerGenerated]
[global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
public partial class TestClass : global::Minerals.AutoDomain.IEntity, global::System.IEquatable<TestClass>
{
    public TestClassId Id { get; private set; }

    public bool Equals(TestClass other)
    {
        return other.Id.Value.Equals(Id.Value);
    }

    public override bool Equals(object obj)
    {
        return obj is TestClass other && other.Id.Value.Equals(Id.Value);
    }

    public override int GetHashCode()
    {
        return Id.Value.GetHashCode();
    }

    public static bool operator ==(TestClass left, TestClass right)
    {
        return left != null && right != null && left.Id.Value.Equals(right.Id.Value);
    }

    public static bool operator !=(TestClass left, TestClass right)
    {
        return (left != null && right == null) || (left == null && right != null) || !left.Id.Value.Equals(right.Id.Value);
    }
}