namespace Minerals.AutoDomain
{
    [Generator]
    public sealed class DomainEventGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var generates = context.SyntaxProvider.ForAttributeWithMetadataName
            (
                "Minerals.AutoDomain.NewDomainEventAttribute",
                static (x, _) => x is MethodDeclarationSyntax,
                static (x, _) => new DomainEventObject(x)
            );

            context.RegisterSourceOutput(generates, static (ctx, element) =>
            {
                for (int i = 0; i < element.Attributes.Length; i++)
                {
                    ctx.AddSource($"{element.Attributes[i].Name}.g.cs", GenerateRecord(element, i));
                }
            });
        }

        private static SourceText GenerateRecord(DomainEventObject eventObj, int attributeIndex)
        {
            var builder = new CodeBuilder();
            builder.AddAutoGeneratedHeader(Assembly.GetExecutingAssembly());
            AppendNamespace(builder, eventObj);

            builder.AddAutoGeneratedAttributes(typeof(ClassDeclarationSyntax));
            AppendRecordHeader(builder, eventObj, attributeIndex);

            var arguments = GetSplitedArguments(eventObj, attributeIndex);
            AppendRecordArguments(builder, arguments);
            AppendRecordConstructorHeader(builder, eventObj, arguments, attributeIndex);
            AppendRecordConstructorBody(builder, arguments);

            builder.CloseAllBlocks();
            return SourceText.From(builder.ToString(), Encoding.UTF8);
        }

        private static void AppendNamespace(CodeBuilder builder, DomainEventObject eventObj)
        {
            if (eventObj.Namespace != string.Empty)
            {
                builder.WriteLine("namespace ")
                    .Write(eventObj.Namespace)
                    .Write(".Events")
                    .OpenBlock();
            }
        }

        private static void AppendRecordHeader(CodeBuilder builder, DomainEventObject eventObj, int attributeIndex)
        {
            builder.WriteLine("public sealed record ")
                .Write(eventObj.Attributes[attributeIndex].Name)
                .Write(" : global::Minerals.AutoDomain.IDomainEvent")
                .OpenBlock();
        }

        private static SplitArgumentObject[] GetSplitedArguments(DomainEventObject eventObj, int attributeIndex)
        {
            var indexOffset = eventObj.Attributes[attributeIndex].IncludeParentId ? 1 : 0;
            var args = new SplitArgumentObject[eventObj.Arguments.Length + indexOffset];
            if (eventObj.Attributes[attributeIndex].IncludeParentId)
            {
                args[0] = GetParentIdSplitedArgument(eventObj);
            }
            for (int i = indexOffset; i < args.Length; i++)
            {
                var array = eventObj.Arguments[i - indexOffset].Split(' ');
                args[i] = new(array[0], array[1].ToPascalCase(), array[1].ToCamelCase());
            }
            return args;
        }

        private static SplitArgumentObject GetParentIdSplitedArgument(DomainEventObject eventObj)
        {
            var parentEventId = $"{eventObj.ParentName}Id";
            return new(parentEventId, parentEventId.ToPascalCase(), parentEventId.ToCamelCase());
        }

        private static void AppendRecordArguments(CodeBuilder builder, SplitArgumentObject[] arguments)
        {
            foreach (SplitArgumentObject arg in arguments)
            {
                builder.WriteLine("public ")
                    .Write(arg.Type)
                    .Write(" ")
                    .Write(arg.PascalCaseName)
                    .Write(" { get; private set; }");
            }
        }

        private static void AppendRecordConstructorHeader(CodeBuilder builder, DomainEventObject eventObj, SplitArgumentObject[] arguments, int attributeIndex)
        {
            builder.NewLine().WriteLine("public ").Write(eventObj.Attributes[attributeIndex].Name).Write("(");
            for (int i = 0; i < arguments.Length; i++)
            {
                builder.Write(arguments[i].Type)
                    .Write(" ")
                    .Write(arguments[i].CamelCaseName);

                if (i < arguments.Length - 1)
                {
                    builder.Write(", ");
                }
            }
            builder.Write(")").OpenBlock();
        }

        private static void AppendRecordConstructorBody(CodeBuilder builder, SplitArgumentObject[] arguments)
        {
            for (int i = 0; i < arguments.Length; i++)
            {
                builder.WriteLine(arguments[i].PascalCaseName)
                    .Write(" = ")
                    .Write(arguments[i].CamelCaseName)
                    .Write(";");
            }
            builder.CloseBlock();
        }
    }
}