global using System;
global using System.Linq;
global using System.Text;
global using System.Reflection;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.Text;
global using Microsoft.CodeAnalysis.CSharp.Syntax;
global using Minerals.AutoDomain.Utils;
global using Minerals.StringCases;