namespace Minerals.AutoDomain.Initialization
{
    [Generator]
    public class AttributesGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            context.RegisterPostInitializationOutput(static (context) =>
            {
                var builder = new CodeBuilder();
                context.AddSource("EntityAttribute.g.cs", GenerateEntityAttribute(builder));
                context.AddSource("AggregateRootAttribute.g.cs", GenerateAggregateRootAttribute(builder));
                context.AddSource("NewDomainAttribute.g.cs", GenerateNewDomainEventAttribute(builder));
            });
        }

        private static SourceText GenerateEntityAttribute(CodeBuilder builder)
        {
            builder.Clear();
            const string source = """
            namespace Minerals.AutoDomain
            {
                [global::System.Diagnostics.DebuggerNonUserCode]
                [global::System.Runtime.CompilerServices.CompilerGenerated]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = true)]
                public sealed class EntityAttribute : global::System.Attribute
                {
                }
            }
            """;
            builder.AddAutoGeneratedHeader(Assembly.GetExecutingAssembly()).WriteLine(source);
            return SourceText.From(builder.ToString(), Encoding.UTF8);
        }

        private static SourceText GenerateAggregateRootAttribute(CodeBuilder builder)
        {
            builder.Clear();
            const string source = """
            namespace Minerals.AutoDomain
            {
                [global::System.Diagnostics.DebuggerNonUserCode]
                [global::System.Runtime.CompilerServices.CompilerGenerated]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                [global::System.AttributeUsage(global::System.AttributeTargets.Class, AllowMultiple = false, Inherited = true)]
                public sealed class AggregateRootAttribute : global::System.Attribute
                {
                }
            }
            """;
            builder.AddAutoGeneratedHeader(Assembly.GetExecutingAssembly()).WriteLine(source);
            return SourceText.From(builder.ToString(), Encoding.UTF8);
        }

        private static SourceText GenerateNewDomainEventAttribute(CodeBuilder builder)
        {
            builder.Clear();
            const string source = """
            #pragma warning disable CS9113
            namespace Minerals.AutoDomain
            {
                [global::System.Diagnostics.DebuggerNonUserCode]
                [global::System.Runtime.CompilerServices.CompilerGenerated]
                [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
                [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true, Inherited = false)]
                public sealed class NewDomainEventAttribute : global::System.Attribute
                {
                    public NewDomainEventAttribute(string name, bool includeParentId = true)
                    {
                    }
                }
            }
            #pragma warning restore CS9113
            """;
            builder.AddAutoGeneratedHeader(Assembly.GetExecutingAssembly()).WriteLine(source);
            return SourceText.From(builder.ToString(), Encoding.UTF8);
        }
    }
}